// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCS6DQzwaDQpVTxg67OBz168aUTkoiqY',
    appId: '1:916374315823:web:96c9493922edde9fb377da',
    messagingSenderId: '916374315823',
    projectId: 'hijizli',
    authDomain: 'hijizli.firebaseapp.com',
    storageBucket: 'hijizli.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENiZ9M8TxkzQL7Q4jKYwRwOa4O5xlZlA',
    appId: '1:916374315823:android:bd7d10839649be97b377da',
    messagingSenderId: '916374315823',
    projectId: 'hijizli',
    storageBucket: 'hijizli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7Nx2-BtZFplkypRKrGAuYhyYhdQZQaI',
    appId: '1:916374315823:ios:76b8455a4561ac5db377da',
    messagingSenderId: '916374315823',
    projectId: 'hijizli',
    storageBucket: 'hijizli.firebasestorage.app',
    iosBundleId: 'com.example.hijizli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7Nx2-BtZFplkypRKrGAuYhyYhdQZQaI',
    appId: '1:916374315823:ios:76b8455a4561ac5db377da',
    messagingSenderId: '916374315823',
    projectId: 'hijizli',
    storageBucket: 'hijizli.firebasestorage.app',
    iosBundleId: 'com.example.hijizli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALCS6DQzwaDQpVTxg67OBz168aUTkoiqY',
    appId: '1:916374315823:web:653556498a106179b377da',
    messagingSenderId: '916374315823',
    projectId: 'hijizli',
    authDomain: 'hijizli.firebaseapp.com',
    storageBucket: 'hijizli.firebasestorage.app',
  );
}
